//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ChatBot.Model.Models
{
    // [Serializable]
    public partial class BOT_QUESTION
    {
        public int QUESTION_ID { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> QUESTION_TYPE { get; set; }
        public Nullable<int> SCENARIO_ID { get; set; }
        public Nullable<int> PREVQUESTION_ID { get; set; }
        public Nullable<bool> IS_END { get; set; }
        public Nullable<int> RECORD_STATUS { get; set; }
        public Nullable<int> PREVANSWER_ID { get; set; }
        public override string ToString()
        {
            return CONTENT;
        }
    }
}
