//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ChatBot.Model.Models
{
    public partial class BOT_SCENARIO
    {
        public int SCENARIO_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> DOMAIN_ID { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<int> RECORD_STATUS { get; set; }
    }
}
