//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using ChatBot.Model.Abstract;

namespace ChatBot.Model.Models
{
    public partial class BOT_DOMAIN : Auditable,IEntityBase
    {
        public int Id { get; set; }
        public int DOMAIN_ID { get; set; }
        public string DOMAIN { get; set; }
        public Nullable<int> RECORD_STATUS { get; set; }
    }
}
