//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ChatBot.Model.Models
{
    //  [Serializable]
    public partial class BOT_CUSTOMERINFO
    {
        public int CUSTOMER_ID { get; set; }
        public Nullable<int> DOMAIN_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public string PHONE { get; set; }
        public Nullable<int> RECORD_STATUS { get; set; }
    }
}
